/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as ForbiddenIndexRouteImport } from './routes/forbidden/index'
import { Route as SignInSplatRouteImport } from './routes/sign-in/$'
import { Route as ProtectedMensuelleIndexRouteImport } from './routes/_protected/mensuelle/index'
import { Route as ProtectedJournaliereIndexRouteImport } from './routes/_protected/journaliere/index'
import { Route as ProtectedHebdomadaireIndexRouteImport } from './routes/_protected/hebdomadaire/index'
import { Route as ProtectedContactsIndexRouteImport } from './routes/_protected/contacts/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenIndexRoute = ForbiddenIndexRouteImport.update({
  id: '/forbidden/',
  path: '/forbidden/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedMensuelleIndexRoute = ProtectedMensuelleIndexRouteImport.update({
  id: '/mensuelle/',
  path: '/mensuelle/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedJournaliereIndexRoute =
  ProtectedJournaliereIndexRouteImport.update({
    id: '/journaliere/',
    path: '/journaliere/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedHebdomadaireIndexRoute =
  ProtectedHebdomadaireIndexRouteImport.update({
    id: '/hebdomadaire/',
    path: '/hebdomadaire/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedContactsIndexRoute = ProtectedContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/forbidden/': typeof ForbiddenIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/contacts/': typeof ProtectedContactsIndexRoute
  '/hebdomadaire/': typeof ProtectedHebdomadaireIndexRoute
  '/journaliere/': typeof ProtectedJournaliereIndexRoute
  '/mensuelle/': typeof ProtectedMensuelleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/forbidden': typeof ForbiddenIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/contacts': typeof ProtectedContactsIndexRoute
  '/hebdomadaire': typeof ProtectedHebdomadaireIndexRoute
  '/journaliere': typeof ProtectedJournaliereIndexRoute
  '/mensuelle': typeof ProtectedMensuelleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/forbidden/': typeof ForbiddenIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/_protected/contacts/': typeof ProtectedContactsIndexRoute
  '/_protected/hebdomadaire/': typeof ProtectedHebdomadaireIndexRoute
  '/_protected/journaliere/': typeof ProtectedJournaliereIndexRoute
  '/_protected/mensuelle/': typeof ProtectedMensuelleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in/$'
    | '/forbidden/'
    | '/sign-in/'
    | '/api/trpc/$'
    | '/contacts/'
    | '/hebdomadaire/'
    | '/journaliere/'
    | '/mensuelle/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in/$'
    | '/forbidden'
    | '/sign-in'
    | '/api/trpc/$'
    | '/contacts'
    | '/hebdomadaire'
    | '/journaliere'
    | '/mensuelle'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/sign-in/$'
    | '/forbidden/'
    | '/sign-in/'
    | '/api/trpc/$'
    | '/_protected/contacts/'
    | '/_protected/hebdomadaire/'
    | '/_protected/journaliere/'
    | '/_protected/mensuelle/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  SignInSplatRoute: typeof SignInSplatRoute
  ForbiddenIndexRoute: typeof ForbiddenIndexRoute
  SignInIndexRoute: typeof SignInIndexRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden/': {
      id: '/forbidden/'
      path: '/forbidden'
      fullPath: '/forbidden/'
      preLoaderRoute: typeof ForbiddenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/mensuelle/': {
      id: '/_protected/mensuelle/'
      path: '/mensuelle'
      fullPath: '/mensuelle/'
      preLoaderRoute: typeof ProtectedMensuelleIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/journaliere/': {
      id: '/_protected/journaliere/'
      path: '/journaliere'
      fullPath: '/journaliere/'
      preLoaderRoute: typeof ProtectedJournaliereIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/hebdomadaire/': {
      id: '/_protected/hebdomadaire/'
      path: '/hebdomadaire'
      fullPath: '/hebdomadaire/'
      preLoaderRoute: typeof ProtectedHebdomadaireIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/contacts/': {
      id: '/_protected/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ProtectedContactsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedContactsIndexRoute: typeof ProtectedContactsIndexRoute
  ProtectedHebdomadaireIndexRoute: typeof ProtectedHebdomadaireIndexRoute
  ProtectedJournaliereIndexRoute: typeof ProtectedJournaliereIndexRoute
  ProtectedMensuelleIndexRoute: typeof ProtectedMensuelleIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedContactsIndexRoute: ProtectedContactsIndexRoute,
  ProtectedHebdomadaireIndexRoute: ProtectedHebdomadaireIndexRoute,
  ProtectedJournaliereIndexRoute: ProtectedJournaliereIndexRoute,
  ProtectedMensuelleIndexRoute: ProtectedMensuelleIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  SignInSplatRoute: SignInSplatRoute,
  ForbiddenIndexRoute: ForbiddenIndexRoute,
  SignInIndexRoute: SignInIndexRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
