/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as MensuelleIndexRouteImport } from './routes/mensuelle/index'
import { Route as JournaliereIndexRouteImport } from './routes/journaliere/index'
import { Route as HebdomadaireIndexRouteImport } from './routes/hebdomadaire/index'
import { Route as ForbiddenIndexRouteImport } from './routes/forbidden/index'
import { Route as ContactsIndexRouteImport } from './routes/contacts/index'
import { Route as SignInSplatRouteImport } from './routes/sign-in/$'
import { Route as ApiTrpcSplatRouteImport } from './routes/api.trpc.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const MensuelleIndexRoute = MensuelleIndexRouteImport.update({
  id: '/mensuelle/',
  path: '/mensuelle/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournaliereIndexRoute = JournaliereIndexRouteImport.update({
  id: '/journaliere/',
  path: '/journaliere/',
  getParentRoute: () => rootRouteImport,
} as any)
const HebdomadaireIndexRoute = HebdomadaireIndexRouteImport.update({
  id: '/hebdomadaire/',
  path: '/hebdomadaire/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenIndexRoute = ForbiddenIndexRouteImport.update({
  id: '/forbidden/',
  path: '/forbidden/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsIndexRoute = ContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/contacts/': typeof ContactsIndexRoute
  '/forbidden/': typeof ForbiddenIndexRoute
  '/hebdomadaire/': typeof HebdomadaireIndexRoute
  '/journaliere/': typeof JournaliereIndexRoute
  '/mensuelle/': typeof MensuelleIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/contacts': typeof ContactsIndexRoute
  '/forbidden': typeof ForbiddenIndexRoute
  '/hebdomadaire': typeof HebdomadaireIndexRoute
  '/journaliere': typeof JournaliereIndexRoute
  '/mensuelle': typeof MensuelleIndexRoute
  '/sign-in': typeof SignInIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/contacts/': typeof ContactsIndexRoute
  '/forbidden/': typeof ForbiddenIndexRoute
  '/hebdomadaire/': typeof HebdomadaireIndexRoute
  '/journaliere/': typeof JournaliereIndexRoute
  '/mensuelle/': typeof MensuelleIndexRoute
  '/sign-in/': typeof SignInIndexRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in/$'
    | '/contacts/'
    | '/forbidden/'
    | '/hebdomadaire/'
    | '/journaliere/'
    | '/mensuelle/'
    | '/sign-in/'
    | '/api/trpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in/$'
    | '/contacts'
    | '/forbidden'
    | '/hebdomadaire'
    | '/journaliere'
    | '/mensuelle'
    | '/sign-in'
    | '/api/trpc/$'
  id:
    | '__root__'
    | '/'
    | '/sign-in/$'
    | '/contacts/'
    | '/forbidden/'
    | '/hebdomadaire/'
    | '/journaliere/'
    | '/mensuelle/'
    | '/sign-in/'
    | '/api/trpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInSplatRoute: typeof SignInSplatRoute
  ContactsIndexRoute: typeof ContactsIndexRoute
  ForbiddenIndexRoute: typeof ForbiddenIndexRoute
  HebdomadaireIndexRoute: typeof HebdomadaireIndexRoute
  JournaliereIndexRoute: typeof JournaliereIndexRoute
  MensuelleIndexRoute: typeof MensuelleIndexRoute
  SignInIndexRoute: typeof SignInIndexRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensuelle/': {
      id: '/mensuelle/'
      path: '/mensuelle'
      fullPath: '/mensuelle/'
      preLoaderRoute: typeof MensuelleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journaliere/': {
      id: '/journaliere/'
      path: '/journaliere'
      fullPath: '/journaliere/'
      preLoaderRoute: typeof JournaliereIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hebdomadaire/': {
      id: '/hebdomadaire/'
      path: '/hebdomadaire'
      fullPath: '/hebdomadaire/'
      preLoaderRoute: typeof HebdomadaireIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden/': {
      id: '/forbidden/'
      path: '/forbidden'
      fullPath: '/forbidden/'
      preLoaderRoute: typeof ForbiddenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts/': {
      id: '/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof ContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInSplatRoute: SignInSplatRoute,
  ContactsIndexRoute: ContactsIndexRoute,
  ForbiddenIndexRoute: ForbiddenIndexRoute,
  HebdomadaireIndexRoute: HebdomadaireIndexRoute,
  JournaliereIndexRoute: JournaliereIndexRoute,
  MensuelleIndexRoute: MensuelleIndexRoute,
  SignInIndexRoute: SignInIndexRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
